name: Test build and deploy


on:
  push:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Go 
        uses: actions/setup-go@v5
        with:
          go-version: 1.23
      - name: build
        run: go build ./...
        

